# Generated by Django 3.2.10 on 2022-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='action',
            field=models.PositiveIntegerField(blank=True, choices=[(3, ''), (0, 'изменить'), (1, 'добавить'), (2, 'удалить')], default=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(3, ''), (0, 'Функциональный'), (1, 'Декомпозированный'), (2, 'Командный')], default=3, null=True),
        ),
    ]
