# Generated by Django 3.2.10 on 2022-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpiapp', '0002_auto_20220927_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='action',
            field=models.PositiveIntegerField(blank=True, choices=[(3, ''), (0, 'изменить'), (1, 'добавить'), (2, 'удалить')], default=3, verbose_name='Корректировка'),
        ),
        migrations.AlterField(
            model_name='card',
            name='comment',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='card',
            name='comment_AES_DO',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Комментарии по аудиту (АЭС/ДО)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='comment_CA',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Комментарии по аудиту (ЦА)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='card',
            name='function',
            field=models.PositiveIntegerField(choices=[(None, 'Выберите функцию'), (0, 'Экономика и финансы'), (1, 'Сооружение'), (2, 'Международные и новые бизнесы'), (3, 'Производство'), (4, 'Инвестиционная деятельность'), (5, 'Управление персоналом'), (6, 'Управление качеством'), (7, 'Генеральная инспекция'), (8, 'ФАИП и ГОЗ / КВЛ'), (9, 'Сбыт'), (10, 'Корпоративное управление, Правовое обеспечение, Управление имуществом, Непрофильные активы'), (11, 'Инновационная деятельность'), (12, 'Безопасность'), (13, 'Административное управление'), (14, 'Закупки и МТО'), (15, 'Внутренний контроль и аудит'), (16, 'Бухгалтерия')], verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='card',
            name='high_level',
            field=models.CharField(max_length=3000, verbose_name='Верхний уровень'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_worker',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID сотрудника'),
        ),
        migrations.AlterField(
            model_name='card',
            name='low_level',
            field=models.CharField(max_length=3000, verbose_name='Нижний уровень'),
        ),
        migrations.AlterField(
            model_name='card',
            name='method',
            field=models.PositiveIntegerField(choices=[(None, 'Выберите методику расчета КПЭ'), (0, 'Дискретный'), (1, 'Непрерывный'), (2, 'Отсекающий'), (3, 'Понижающий')], verbose_name='Методика расчета'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=3000, verbose_name='Наименование КПЭ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='organization',
            field=models.PositiveIntegerField(choices=[(None, 'Выберите организацию'), (0, 'ЦА'), (1, 'Балаковская АЭС'), (2, 'Белоярская АЭС'), (3, 'Билибинская АЭС'), (4, 'Калининская АЭС'), (5, 'Кольская АЭС'), (6, 'Курская АЭС'), (7, 'Ленинградская АЭС'), (8, 'Нововоронежская АЭС'), (9, 'Ростовская АЭС'), (10, 'Смоленская АЭС'), (11, 'ПАТЭС'), (12, 'Технологический филиал'), (13, 'ОДИЦ ВВЭР'), (14, 'ОДИЦ РБМК'), (15, 'Строящаяся Балтийская АЭС'), (16, 'ИЦ Аккую'), (17, 'Воронежская АСТ'), (18, 'Филиал в Бангладеш'), (19, 'Атомтехэнерго'), (20, 'АтомЭнергоСбыт'), (21, 'АтомЭнергоРемонт'), (22, 'ЗАЭС'), (23, 'АтомТеплоЭлектроСеть'), (24, 'Техническая Академия'), (25, 'ИКАО'), (26, 'НИЦ АЭС'), (27, 'ЭНИЦ'), (28, 'Энергоатоминвест'), (29, 'Балтийская АЭС, АО'), (30, 'Атомтранс'), (31, 'Атомтеплосбыт'), (32, 'ВНИИАЭС'), (33, 'Титан - 2'), (34, 'Консист - ОС'), (35, 'С - Плюс'), (36, 'Неорганические сорбенты'), (37, 'АТОМДАТА'), (38, 'Атомдата - Центр'), (39, 'Атомдата - Иннополис')], verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='card',
            name='path_to_doc',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='card',
            name='target_level',
            field=models.CharField(max_length=3000, verbose_name='Целевой уровень'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(3, ''), (0, 'Функциональный'), (1, 'Декомпозированный'), (2, 'Командный')], default=3, null=True, verbose_name='Тип КПЭ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='weight',
            field=models.IntegerField(verbose_name='Вес'),
        ),
    ]
